### ISSUE TITLE
Documentation improvements 

### ISSUE THREAD

**Issue by RusseII** [multisig-labs/knowledgebase#1]
Some improvements you can make in https://github.com/multisig-labs/knowledgebase/blob/main/avalanche.md

> Ethereum only can process about 15 transactions per second

This is `technically` true if referring to mainnet ethereum - but it misrepresents reality. [See current TPS](https://ethtps.info/)

Here's [an article]( https://ethereum-magicians.org/t/a-rollup-centric-ethereum-roadmap/4698
) by vitalik that outlines ethereum's scaling strategy 

> Today, Ethereum has ~15 TPS.
If everyone moves to rollups, we will soon have ~3000 TPS.
Once phase 1 comes along and rollups move to eth2 sharded chains for their data storage, we go up to a theoretical max of ~100000 TPS.
Eventually, phase 2 will come along, bringing eth2 sharded chains with native computations, which give us… ~1000-5000 TPS.

> Ethereum is moving to Proof of Stake with 2.0).

No longer called 2.0 - It's been renamed! https://blog.ethereum.org/2022/01/24/the-great-eth2-renaming/

**Comment by chand1012** [comment]
Thank you for the feedback! I will update the documentation in the near future.

**Comment by chand1012** [comment]
Fixed with bbc2c7407cb801f0dc01f604bc26f5a371ecbf58. Thanks @RusseII!
